general.import = [
	"~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
padding.x = 10
padding.y = 10

opacity = 0.8
blur = true

startup_mode = "Maximized"

